In [1]:
!pip install geopy
import geopandas as gpd
shapefile = './data/countries_110m/ne_110m_admin_0_countries.shp'
#Read shapefile using Geopandas
gdf = gpd.read_file(shapefile)[['ADMIN', 'ADM0_A3', 'geometry']]
#Rename columns.
gdf.columns = ['country', 'country_code', 'geometry']
gdf.head()

Error initializing plugin EntryPoint(name='Windows (alt)', value='keyrings.alt.Windows', group='keyring.backends').
Traceback (most recent call last):
  File "/home/vmuser/.local/lib/python3.6/site-packages/keyring/backend.py", line 203, in _load_plugins
    init_func = ep.load()
  File "/usr/local/lib/python3.6/dist-packages/importlib_metadata/__init__.py", line 95, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/keyrings/alt/Windows.py", line 9, in <module>
    from . import file_base
  File "/usr/lib/python3/dist-packages/keyrings/alt/file_base.py", line 13, in <module>
    from keyring.util.escape import escape as escape_for_ini
ModuleNotFoundError: No module named 'keyring.util.escape'
Error initializing plugin EntryPoint(name='file', value='keyrings.alt.file', group='keyring.backends').
Traceback (most recent call last):
  File "/home/vmuser/.local/lib/python3.6/site-packages/keyring/backend.py", line 203, in _load_plugins
    init_func = ep.load()
  File "/usr/local/lib/python3.6/dist-packages/importlib_metadata/__init__.py", line 95, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/keyrings/alt/file.py", line 11, in <module>
    from keyring.util.escape import escape as escape_for_ini
ModuleNotFoundError: No module named 'keyring.util.escape'
Error initializing plugin EntryPoint(name='pyfs', value='keyrings.alt.pyfs', group='keyring.backends').
Traceback (most recent call last):
  File "/home/vmuser/.local/lib/python3.6/site-packages/keyring/backend.py", line 203, in _load_plugins
    init_func = ep.load()
  File "/usr/local/lib/python3.6/dist-packages/importlib_metadata/__init__.py", line 95, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/keyrings/alt/pyfs.py", line 8, in <module>
    from keyring.util.escape import escape as escape_for_ini
ModuleNotFoundError: No module named 'keyring.util.escape'
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: geopy in /home/vmuser/.local/lib/python3.6/site-packages (1.21.0)
Requirement already satisfied: geographiclib<2,>=1.49 in /home/vmuser/.local/lib/python3.6/site-packages (from geopy) (1.50)

,country,country_code,geometry
0,Fiji,FJI,"MULTIPOLYGON (((180.00000 -16.06713, 180.00000..."
1,United Republic of Tanzania,TZA,"POLYGON ((33.90371 -0.95000, 34.07262 -1.05982..."
2,Western Sahara,SAH,"POLYGON ((-8.66559 27.65643, -8.66512 27.58948..."
3,Canada,CAN,"MULTIPOLYGON (((-122.84000 49.00000, -122.9742..."
4,United States of America,USA,"MULTIPOLYGON (((-122.84000 49.00000, -120.0000..."

In [2]:
print(gdf[gdf['country'] == 'Antarctica'])
#Drop row corresponding to 'Antarctica'
gdf = gdf.drop(gdf.index[159])

        country country_code  \
159  Antarctica          ATA

                                              geometry
159  MULTIPOLYGON (((-48.66062 -78.04702, -48.15140...

In [3]:
grid_crs=gdf.crs
grid_crs

<Geographic 2D CRS: EPSG:4326>
Name: WGS 84
Axis Info [ellipsoidal]:
- Lat[north]: Geodetic latitude (degree)
- Lon[east]: Geodetic longitude (degree)
Area of Use:
- name: World
- bounds: (-180.0, -90.0, 180.0, 90.0)
Datum: World Geodetic System 1984
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich

In [4]:
import json
#Read data to json.
gdf_json = json.loads(gdf.to_json())
#Convert to String like object.
grid = json.dumps(gdf_json)

In [5]:
import pandas as pd
datafile = './data/coronavirus.csv'
#Read csv file using pandas
df = pd.read_csv(datafile, names = ['continent', 'country/territory', 'confirmed_cases', 'deaths'], skiprows = 1)
df.head()

  continent  country/territory  confirmed_cases  deaths
0      Asia              China            37242     812
1      Asia          Singapore               40       0
2      Asia           Thailand               32       0
3      Asia              Japan               26       0
4      Asia  Republic of Korea               25       0

In [6]:
from geopy.geocoders import Nominatim
geolocator = Nominatim(user_agent="my_Dashboard")
import numpy as np
def geolocate(city=None, country=None):
    '''
    Inputs city and country, or just country. Returns the lat/long coordinates of 
    either the city if possible, if not, then returns lat/long of the center of the country.
    '''
    try:
            # Geolocate the center of the country
        loc = geolocator.geocode(country)
            # And return latitude and longitude 
        return (loc.latitude, loc.longitude)
        # Otherwise
    except:
            # Return missing value
        return np.nan

In [7]:
geolocate(country='China')

(35.000074, 104.999927)

In [8]:
df['location'] = df['country/territory'].apply(geolocate)

In [9]:
df['scaled_confirmed_cases'] = np.log10(df['confirmed_cases'])*10
df

,continent,country/territory,confirmed_cases,deaths,location,scaled_confirmed_cases
0,Asia,China,37242,812,"(44.933143, 7.540121)",45.710330
1,Asia,Singapore,40,0,"(44.933143, 7.540121)",16.020600
2,Asia,Thailand,32,0,"(44.933143, 7.540121)",15.051500
3,Asia,Japan,26,0,"(44.933143, 7.540121)",14.149733
4,Asia,Republic of Korea,25,0,"(44.933143, 7.540121)",13.979400
5,Asia,Taiwan,18,0,"(44.933143, 7.540121)",12.552725
6,Asia,Malaysia,16,0,"(44.933143, 7.540121)",12.041200
7,Asia,Vietnam,14,0,"(44.933143, 7.540121)",11.461280
8,Asia,United Arab Emirates,7,0,"(44.933143, 7.540121)",8.450980
9,Asia,India,3,0,"(44.933143, 7.540121)",4.771213
10,Asia,Philippines,3,1,"(44.933143, 7.540121)",4.771213
11,Asia,Nepal,1,0,"(44.933143, 7.540121)",0.000000
12,Asia,Sri Lanka,1,0,"(44.933143, 7.540121)",0.000000
13,Asia,Cambodia,1,0,"(44.933143, 7.540121)",0.000000
14,Other,Cases on an international conveyance Japan,64,0,"(44.933143, 7.540121)",18.061800
15,Europe,Germany,14,0,"(44.933143, 7.540121)",11.461280
16,Europe,France,11,0,"(44.933143, 7.540121)",10.413927
17,Europe,Italy,3,0,"(44.933143, 7.540121)",4.771213
18,Europe,United Kingdom,3,0,"(44.933143, 7.540121)",4.771213
19,Europe,Russia,2,0,"(44.933143, 7.540121)",3.010300
20,Europe,Finland,1,0,"(44.933143, 7.540121)",0.000000
21,Europe,Belgium,1,0,"(44.933143, 7.540121)",0.000000
22,Europe,Spain,1,0,"(44.933143, 7.540121)",0.000000
23,Europe,Sweden,1,0,"(44.933143, 7.540121)",0.000000
24,America,United States of America,12,0,"(44.933143, 7.540121)",10.791812
25,America,Canada,7,0,"(44.933143, 7.540121)",8.450980
26,Oceania,Australia,15,0,"(44.933143, 7.540121)",11.760913

In [10]:
df[['lat','lon']] = pd.DataFrame(df['locations'].tolist(),index=df.index)
df.head()

KeyError: 'locations'

In [ ]:
datapoints=df.drop(['locations'], axis=1)
datapoints.head()

In [ ]:
from bokeh.io import output_notebook, show, output_file
from bokeh.plotting import figure
from bokeh.models import GeoJSONDataSource, ColumnDataSource
#Input GeoJSON source that contains features for plotting.
geosource = GeoJSONDataSource(geojson = grid)
pointsource = ColumnDataSource(datapoints)

#Create figure object.
p = figure(title = 'Geographic distribution of 2019-nCov cases worldwide', plot_height = 600 , plot_width = 950)
p.xgrid.grid_line_color = None
p.ygrid.grid_line_color = None
#Add patch renderer to figure. 
p.patches('xs','ys', source = geosource,fill_color = 'lightgrey',
          line_color = 'black', line_width = 0.25, fill_alpha = 1)

p.circle('lat','lon',source=pointsource, size=15)
#Display figure inline in Jupyter Notebook.
output_notebook()
#Display figure.
show(p)